version: "3.8"
services:
  web:
    image: localhost:5000/simple-arm7-web:2025-10-29

    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host

    read_only: true
    volumes:
      - type: bind
        source: /home/analyst/website/site
        target: /usr/share/nginx/html
        read_only: true
      - type: tmpfs
        target: /tmp
      - type: tmpfs
        target: /run
      - type: tmpfs
        target: /var/cache/nginx

    # Create/chown temp dir before workers drop privs
    command:
      - /bin/sh
      - -lc
      - |
        set -e
        mkdir -p /tmp/client_temp
        chown -R 101:101 /tmp/client_temp
        exec nginx -g 'daemon off;'

    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8080/ >/dev/null"]
      interval: 30s
      timeout: 3s
      retries: 3

    deploy:
      mode: replicated
      replicas: 1
      restart_policy: { condition: on-failure }
      update_config:
        order: start-first
        parallelism: 1
        delay: 5s
