version: "3.8"
services:
  web:
    image: nginx:alpine
    ports:
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    read_only: true
    volumes:
      - ./site:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/analyst/socket23_cert:/etc/nginx/certs:ro
      - type: tmpfs
        target: /tmp
      - type: tmpfs
        target: /run
      - type: tmpfs
        target: /var/cache/nginx

    # Create/chown temp dir before workers drop privs
    command:
      - /bin/sh
      - -lc
      - |
        set -e
        mkdir -p /tmp/client_temp
        chown -R 101:101 /tmp/client_temp
        exec nginx -g 'daemon off;'

    healthcheck:
      test: ["CMD-SHELL", "wget -qO- --no-check-certificate https://127.0.0.1:443/ >/dev/null"]
      interval: 30s
      timeout: 3s
      retries: 3

    deploy:
      mode: replicated
      replicas: 1
      restart_policy: { condition: on-failure }
      update_config:
        order: stop-first
        parallelism: 1
        delay: 5s
